# Publish docs to GitLab Pages
# see: https://squidfunk.github.io/mkdocs-material/publishing-your-site/#gitlab-pages
#
image: python:3.9.9-slim-bullseye
pages:
  stage: deploy
  only:
    - main
  script:
    # install dependencies for mkdocs-git-revision-date-plugin
    - apt update && apt-get install -y git
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public
