# Publish docs to GitLab Pages
# see: https://squidfunk.github.io/mkdocs-material/publishing-your-site/#gitlab-pages
#
default:
  image:
    name: squidfunk/mkdocs-material:9.5.24
    entrypoint: [""]


stages:
  - lint
  - build
  - deploy

pre-commit:
  stage: lint
  script:
    - pip install pre-commit
    # skip markdownlint and run it in a separate job since it requires node
    - SKIP="markdownlint-cli2" pre-commit run --all

markdownlint:
  stage: lint
  image:
    name: davidanson/markdownlint-cli2-rules:v0.13.0
    # overwrite default entrypoint (which is a call to markdownlint-cli2)
    entrypoint: [""]
  script:
    # use the config file that is stored outside the root
    - markdownlint-cli2 --config .gitlab/markdownlint/.markdownlint-cli2.yaml "**/*.md"
  artifacts:
    when: always
    reports:
      codequality: markdownlint-cli2-codequality.json

build:
  stage: build
  variables:
    # fetch the full git history to be able to determine creation dates for pages
    # see: https://github.com/timvink/mkdocs-git-revision-date-localized-plugin?tab=readme-ov-file#note-when-using-build-environments
    GIT_DEPTH: 0
  script:
    - pip install -r requirements.txt
    - mkdocs --version
    - mkdocs build --strict --site-dir public
  artifacts:
    expire_in: 7 days
    paths:
      - public

pages:
  stage: deploy
  rules:
    # deploy only on default branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - mkdocs --version
  artifacts:
    paths:
      - public


workflow:
  # auto cancel redundant pipelines
  # https://docs.gitlab.com/ee/ci/pipelines/settings.html#auto-cancel-redundant-pipelines
  # https://docs.gitlab.com/ee/ci/yaml/index.html#workflowauto_cancelon_new_commit
  auto_cancel:
    on_new_commit: interruptible

include:
  # run pipelines for default branch, tags, and all types of merge request pipelines
  # to support merge trains
  # see: https://docs.gitlab.com/ee/ci/pipelines/merge_trains.html#enable-merge-trains
  # https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Workflows/MergeRequest-Pipelines.gitlab-ci.yml
  - template: Workflows/MergeRequest-Pipelines.gitlab-ci.yml
