line-length: false

ul-indent:
  indent: 4

# Allow inline HTML to support image captions
MD033: false

# Allow bare URLs since we use magiclink to convert bare URLs automatically to links
MD034: false

# Need to disable in order to support PyMdown Tabbed extension
# See: https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/
MD046: false

max-one-sentence-per-line:
  ignored_words:
    - "ie"
    - "i.e"
    - "eg"
    - "e.g"
    - "etc"
    - "ex"
    - "!!"
    - "??"
