# https://github.com/DavidAnson/markdownlint?tab=readme-ov-file#rules--aliases

line-length: false

ul-indent:
  indent: 4

# Allow inline HTML to support image captions
MD033: false

# Allow bare URLs since we use magiclink to convert bare URLs automatically to links
MD034: false

# Need to disable in order to support PyMdown Tabbed extension
# See: https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/
MD046: false

# Allow same heading name if the parent is different
MD024:
  siblings_only: true

max-one-sentence-per-line:
  # ignore admonition syntax
  # see: https://github.com/aepfli/markdownlint-rule-max-one-sentence-per-line/pull/52/files#r1579994724
  ignored_words:
    - "ie"
    - "i.e"
    - "eg"
    - "e.g"
    - "etc"
    - "ex"
    - "!!"
    - "??"
    - "vs"
