# SPDX-FileCopyrightText: Copyright (C) 2024 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>
#
# SPDX-License-Identifier: MIT

# https://github.com/DavidAnson/markdownlint-cli2#markdownlint-cli2yaml

ignores:
  - ".gitlab/merge_request_templates/Default.md"

gitignore: true
