# SPDX-FileCopyrightText: Copyright (C) 2022 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>
#
# SPDX-License-Identifier: MIT

# https://github.com/DavidAnson/markdownlint?tab=readme-ov-file#rules--aliases

line-length: false

ul-indent:
  indent: 4

# Allow inline HTML to support image captions
no-inline-html: false

# Allow screenshots to have no alt text
no-alt-text: false

# Allow bare URLs since we use magiclink to convert bare URLs automatically to links
no-bare-urls: false

# Need to disable in order to support PyMdown Tabbed extension
# See: https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/
code-block-style: false

# Allow same heading name if the parent is different
no-duplicate-heading:
  siblings_only: true

max-one-sentence-per-line:
  # ignore admonition syntax
  # see: https://github.com/aepfli/markdownlint-rule-max-one-sentence-per-line/pull/52/files#r1579994724
  ignored_words:
    - "ie"
    - "i.e"
    - "eg"
    - "e.g"
    - "etc"
    - "ex"
    - "!!"
    - "??"
    - "vs"

# mkdocs-material-linter
# see: https://github.com/mensfeld/mkdocs-material-linter?tab=readme-ov-file#provided-rules
material-meta-tags: false
# disabled due to code blocks with more than 3 backticks
# https://github.com/mensfeld/mkdocs-material-linter/issues/24
material-blank-lines-spacing: false
material-code-block-syntax: false
