# SPDX-FileCopyrightText: Copyright (C) 2024 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>
#
# SPDX-License-Identifier: MIT

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-json
        # file contains comments
        exclude: |
          (?x)(
            ^(
              \.vscode/settings\.json
              |\.vscode/extensions\.json
              |\.devcontainer/devcontainer.json
            )
          )
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        # exclude mkdocs.yml because it contains custom tags
        exclude: ^mkdocs\.yml$
      # check yaml only for syntax (some contain unrecognized tags)
      - id: check-yaml
        name: check-yaml syntax only
        args: ["--unsafe"]
        files: ^mkdocs\.yml$
      - id: detect-private-key
      - id: end-of-file-fixer

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        language: python
        additional_dependencies:
          - mdformat-mkdocs==4.4.1
          - mdformat-footnote==0.1.1

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.15
    hooks:
      - id: uv-lock

  - repo: https://github.com/crate-ci/typos
    rev: v1.36.2
    hooks:
      - id: typos

  - repo: https://github.com/fsfe/reuse-tool
    rev: v5.1.1
    hooks:
      - id: reuse-lint-file

  # zizmor detects security vulnerabilities in GitHub Actions workflows.
  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: v1.12.1
    hooks:
      - id: zizmor

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.33.3
    hooks:
      - id: check-github-workflows
        args: ["--verbose"]
      - id: check-compose-spec
        args: ["--verbose"]
      - id: check-renovate
        args: ["--verbose"]
        additional_dependencies: ['json5']
      # requires: https://github.com/python-jsonschema/check-jsonschema/issues/341
      # - id: check-jsonschema
      #   name: "Validate devcontainer"
      #   files: ^\.devcontainer/.*\.json$
      #   args: ["--schemafile", "https://raw.githubusercontent.com/devcontainers/spec/main/schemas/devContainer.schema.json"]
      # waiting for custom YAML tags support: https://github.com/python-jsonschema/check-jsonschema/issues/489
      # - id: check-jsonschema
      #   name: "Validate MkDocs file"
      #   files: ^mkdocs\.ya?ml$
      #   types: [yaml]
      #   args: ["--verbose", "--schemafile", "https://squidfunk.github.io/mkdocs-material/schema.json"]

  # `actionlint` hook, for verifying correct syntax in GitHub Actions workflows.
  # Some additional configuration for `actionlint` can be found in `.github/actionlint.yaml`.
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
        language: golang
        additional_dependencies:
          # actionlint has a shellcheck integration which extracts shell scripts in `run:` steps from GitHub Actions
          # and checks these with shellcheck. This is arguably its most useful feature,
          # but the integration only works if shellcheck is installed
          - "github.com/wasilibs/go-shellcheck/cmd/shellcheck@v0.10.0"
