repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-json
        # file contains comments
        exclude: ^\.vscode/settings.json$
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        # exclude mkdocs.yml because it contains custom tags
        exclude: ^mkdocs\.yml$
      # check yaml only for syntax (some contain unrecognized tags)
      - id: check-yaml
        name: check-yaml syntax only
        args: ["--unsafe"]
        files: ^mkdocs\.yml$
      - id: detect-private-key
      - id: end-of-file-fixer

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.13.0
    hooks:
      - id: markdownlint-cli2
