# https://github.com/DavidAnson/markdownlint-cli2#markdownlint-cli2yaml

# markdownlint config
# extend the default markdownlint-cli2 config
# config:
  # extends: "../../.markdownlint-cli2.yaml"

customRules:
  # Enforce one sentence per line
  # See: https://github.com/DavidAnson/markdownlint/pull/719
  - "markdownlint-rule-max-one-sentence-per-line"

outputFormatters:
  - - markdownlint-cli2-formatter-default
  - - markdownlint-cli2-formatter-codequality
